allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@nkzw/oxlint-config@2.0.1'
catalog:
  '@vitest/coverage-v8': 4.1.11
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
overrides:
  vite@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
